# Generated by Django 5.2.17 on 2026-09-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_withdrawn_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='network',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stellar_address',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('usdc', 'USDC simulation'), ('bank_card', 'Bank / card simulation'), ('stellar_usdc_testnet', 'Stellar USDC testnet')], max_length=32),
        ),
    ]
