# Generated by Django 5.2.17 on 2026-09-25 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='agreement_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assignment',
            name='client_response_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='revisions_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='acceptance_criteria',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('review', 'Needs review'), ('removed', 'Removed')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='response_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='job',
            name='revision_limit',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='submission',
            name='evidence',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.CreateModel(
            name='AccountSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('warning', 'Warning'), ('suspension', 'Suspension'), ('ban', 'Ban')], max_length=20)),
                ('reason', models.TextField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_sanctions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=2000)),
                ('evidence', models.TextField(blank=True, max_length=3000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('release', 'Release to worker'), ('refund', 'Refund client'), ('split', 'Split'), ('revision', 'Return for revision'), ('cancel', 'Cancel agreement')], max_length=20)),
                ('split_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='core.assignment')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_disputes', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
