# Generated by Django 5.2.17 on 2026-09-25 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assignment_agreement_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='terms_version',
            field=models.CharField(default='2026-09-25', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('AI & Automation', 'AI & Automation'), ('Art & Illustration', 'Art & Illustration'), ('Audio & Music', 'Audio & Music'), ('Business Consulting', 'Business Consulting'), ('Community Management', 'Community Management'), ('Content Writing', 'Content Writing'), ('Customer Support', 'Customer Support'), ('Data & Analytics', 'Data & Analytics'), ('Graphic Design', 'Graphic Design'), ('Marketing & Growth', 'Marketing & Growth'), ('Mobile Development', 'Mobile Development'), ('Operations', 'Operations'), ('Photography', 'Photography'), ('Product Management', 'Product Management'), ('Research', 'Research'), ('Sales', 'Sales'), ('Social Media', 'Social Media'), ('Translation', 'Translation'), ('UI/UX Design', 'UI/UX Design'), ('Video Editing', 'Video Editing'), ('Virtual Assistance', 'Virtual Assistance'), ('Web Development', 'Web Development'), ('Web3 & Blockchain', 'Web3 & Blockchain')], max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('review', 'Needs review'), ('removed', 'Removed')], default='review', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
