# Generated by Django 5.2.17 on 2026-09-27 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_staff(apps, schema_editor):
    User=apps.get_model('core','User')
    StaffAccess=apps.get_model('core','StaffAccess')
    for user in User.objects.filter(is_staff=True,is_active=True):
        StaffAccess.objects.get_or_create(
            user=user,
            defaults={
                'role':'owner' if user.is_superuser else 'moderator',
                'status':'approved',
                'approved_at':user.date_joined,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_waitlistapplication_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('moderator', 'Moderator'), ('support', 'Support')], default='moderator', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_staff_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(preserve_existing_staff,migrations.RunPython.noop),
    ]
