# Generated by Django 5.2.17 on 2026-09-28 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsanction',
            name='lift_reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='accountsanction',
            name='lifted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountsanction',
            name='lifted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifted_sanctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
