# Generated by Django 5.2.17 on 2026-09-28 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect_activity(apps, schema_editor):
    # Django owns this server-only table; it must not be exposed via Supabase REST.
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE core_accountactivity ENABLE ROW LEVEL SECURITY')
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')")
            for (role,) in cursor.fetchall():
                schema_editor.execute(f'REVOKE ALL ON core_accountactivity FROM "{role}"')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ticketfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='one_activity_per_account_day')],
            },
        ),
        migrations.RunPython(protect_activity, migrations.RunPython.noop),
    ]
