# Generated by Django 5.2.17 on 2026-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_accountactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratebucket',
            name='expires',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['worker', '-created_at'], name='application_worker_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['worker', 'status', '-created_at'], name='assignment_worker_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', '-created_at'], name='audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['status', '-created_at'], name='email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'moderation_status', '-created_at'], name='job_public_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='notification_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-updated_at'], name='support_queue_idx'),
        ),
    ]
