# Generated by Django 5.2.17 on 2026-10-01 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_trust_support_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('collaboration', 'Find collaborators'), ('skills', 'Skill exchange'), ('stellar', 'Stellar builders'), ('question', 'Ask the community'), ('showcase', 'Share progress')], max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(max_length=3000)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills that help people find this post.', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Open'), ('closed', 'Closed'), ('removed', 'Removed')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.communitypost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading content'), ('harassment', 'Harassment or abuse'), ('unsafe', 'Unsafe payment or credential request'), ('illegal', 'Prohibited or unlawful activity'), ('other', 'Other concern')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.communitypost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_community_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['status', 'topic', '-updated_at'], name='community_feed_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityreport',
            constraint=models.UniqueConstraint(fields=('post', 'reporter'), name='one_community_report_per_member'),
        ),
    ]
