# Generated by Django 5.2.17 on 2026-10-04 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_emaildelivery_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=56)),
                ('asset', models.CharField(choices=[('XLM', 'Test XLM'), ('USDC', 'Test USDC')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=7, max_digits=18)),
                ('memo', models.CharField(blank=True, max_length=28)),
                ('network', models.CharField(default='stellar_testnet', editable=False, max_length=20)),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transfer', to='core.assignment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
