# Generated by Django 5.2.17 on 2026-10-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_wallettransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('awaiting_acceptance', 'Awaiting agreement'), ('awaiting_funding', 'Awaiting payment route'), ('funded', 'Ready for work'), ('submitted', 'Ready for review'), ('paid', 'Completed · see payment record'), ('disputed', 'Dispute open'), ('cancelled', 'Cancelled')], default='awaiting_acceptance', max_length=24),
        ),
    ]
