# Generated by Django 5.2.17 on 2026-10-05 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='escrow_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_asset',
            field=models.CharField(choices=[('USDC', 'Test USDC'), ('XLM', 'Test XLM')], default='USDC', max_length=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.PositiveIntegerField(help_text='Fixed number of selected testnet tokens, not a live currency conversion.'),
        ),
        migrations.CreateModel(
            name='EscrowAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=56)),
                ('agreement_id', models.CharField(max_length=64, unique=True)),
                ('client_address', models.CharField(max_length=56)),
                ('worker_address', models.CharField(max_length=56)),
                ('reviewer_address', models.CharField(max_length=56)),
                ('asset', models.CharField(max_length=4)),
                ('token_address', models.CharField(max_length=56)),
                ('amount', models.PositiveBigIntegerField()),
                ('deadline', models.PositiveBigIntegerField()),
                ('review_seconds', models.PositiveIntegerField()),
                ('revision_limit', models.PositiveSmallIntegerField()),
                ('chain_status', models.CharField(default='Unfunded', max_length=20)),
                ('review_until', models.PositiveBigIntegerField(default=0)),
                ('funded_hash', models.CharField(blank=True, max_length=64)),
                ('settlement_hash', models.CharField(blank=True, max_length=64)),
                ('worker_paid', models.PositiveBigIntegerField(default=0)),
                ('client_refunded', models.PositiveBigIntegerField(default=0)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('xlm_acknowledged', models.BooleanField(default=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='core.assignment')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=24)),
                ('source', models.CharField(max_length=56)),
                ('prepared_xdr', models.TextField()),
                ('signed_xdr', models.TextField(blank=True)),
                ('tx_hash', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(default='prepared', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.escrowagreement')),
            ],
        ),
    ]
