# Generated by Django 5.2.17 on 2026-10-06 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_assignment_escrow_required_job_payment_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowagreement',
            name='staff_governed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EscrowStaffOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=16)),
                ('contract', models.CharField(blank=True, max_length=56)),
                ('source', models.CharField(max_length=56)),
                ('wallet', models.CharField(max_length=56)),
                ('role', models.PositiveSmallIntegerField(default=0)),
                ('prepared_xdr', models.TextField()),
                ('signed_xdr', models.TextField(blank=True)),
                ('tx_hash', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(default='prepared', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_staff_operations', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_access_operations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowStaffWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=56, unique=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_staff_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
